import './category.dart';
import './meal.dart';

const categoryList = const [
  Category(
      id: 'c1',
      title: 'Myanmar',
      imageURL:
          'https://thumbs.dreamstime.com/b/myanmar-country-text-red-love-heart-suitable-logo-icon-typography-design-138739407.jpg'),
  Category(
      id: 'c2',
      title: 'Japan',
      imageURL:
          'https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/flag-of-japan-word-roy-pedersen.jpg'),
  Category(
      id: 'c3',
      title: 'Chinese',
      imageURL:
          'https://thumbs.dreamstime.com/z/chinese-word-text-logo-icon-red-circle-design-white-background-suitable-card-typography-147082105.jpg?w=992'),
  Category(
      id: 'c4',
      title: 'Thailand',
      imageURL:
          'https://www.shutterstock.com/image-vector/thailand-typography-calligraphy-style-brush-260nw-1364741195.jpg'),
  Category(
      id: 'c5',
      title: 'Korea',
      imageURL:
          'https://sites.psu.edu/jee1117/wp-content/uploads/sites/13114/2014/06/korea1.png'),
  Category(
      id: 'c6',
      title: 'All',
      imageURL:
          'https://logos.flamingtext.com/Word-Logos/all-design-girls-name.png'),
  Category(
      id: 'c7',
      title: 'Breakfast',
      imageURL:
          'https://i0.wp.com/freefontdl.com/wp-content/uploads/2022/03/breakfast-font_622e91ff29b78.jpeg?fit=768%2C512&ssl=1'),
  Category(
      id: 'c8',
      title: 'Lunch',
      imageURL:
          'https://media.istockphoto.com/id/1181750496/vector/lets-do-lunch-hand-drawn-vector-lettering-phrase-cartoon-style.jpg?s=612x612&w=0&k=20&c=2IgPhXb3ks3MOoCr-_lV_PDBspA-oc1KEwa7k571sDY='),
  Category(
      id: 'c9',
      title: 'dinner',
      imageURL:
          'https://timbervalleyskp.com/wp-content/uploads/2018/01/Dinner-clipart.jpg'),
];

const MealsList = const [
  Meal(
    id: 'm1',
    title: 'Mohinga',
    imgURL:
        'https://img.i-scmp.com/cdn-cgi/image/fit=contain,width=1098,format=auto/sites/default/files/styles/1200x800/public/d8/images/methode/2019/11/19/399d0bd8-05f4-11ea-a68f-66ebddf9f136_image_hires_124523.jpg?itok=_GncwaWt&v=1574138728',
    categories: ['c1', 'c6', 'c7'],
    ingredients: [
      '2 white onions chopped',
      'lb tilapia or catfish fillet',
      '1-inch piece fresh ginger chopped',
      '5 cloves garlic minced',
      '8 tablespoons vegetable oil',
      '3 teaspoons turmeric',
      '2 teaspoons paprika',
      '8 tablespoons rice flour or chickpea flour',
      '3 stalks lemongrass',
      '2 teaspoons dashi powder',
      '8 tablespoons fish sauce',
      '1 lb rice noodles',
      '1 bunch cilantro coarsely chopped',
      '3 hard-boiled eggs halved',
      '2 limes quartered',
      'Crushed red pepper',
    ],
    steps: [
      'Cut about 2 inches (5cm) from the base of each lemongrass stalks and thinly slice those pieces.',
      'Vigorously pound the remaining piece of each lemongrass stalk and cut each stalk into 3 inch (8cm) sections.',
      'The thinly sliced lemongrass rings will be fried and the long sections will be used for the broth.',
      'Prepare the broth by bringing 10 cups (2,5l) of water to a boil in a large saucepan with the dashi powder and 2 tablespoons of fish sauce.',
      'Add the pounded lemongrass sections, and the fish fillets. Simmer for about 10 minutes until the fish is cooked through.',
      'In a skillet, heat the oil over medium/high heat. When the oil is hot enough, add the chopped onion, garlic, ginger and thinly sliced lemongrass. Sauté for 3	-4 minutes.',
      'Reduce heat to medium. Add turmeric, paprika, 1 tablespoon of fish sauce and a pinch of salt. Cook over medium heat for about 5 minutes, stirring 	occasionally.',
      'Meanwhile, remove the filets from the pot. Using two forks, coarsely chop the fish as thinly as possible.',
      'Add the fish to the mixture in the pan. Increase heat to medium/high, and cook the fish with the sauce for about 10 minutes, stirring vigorously and fairly 	regularly.',
      'Place fish mixture into the broth and bring to a boil again.',
      'Add the other 4 tablespoons of fish sauce. Add the rice flour and stir. Bring to a boil and let the broth simmer for about 15 minutes or until the broth has 	considerably thickened.',
      'In each individual bowl, add noodles and cover with broth. Put half a boiled egg on top, and sprinkle cilantro and crushed pepper. Serve with a wedge of 	lime.',
    ],
    duration: 45,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm2',
    title: 'Burmese Khow Suey',
    imgURL:
        'https://sp-ao.shortpixel.ai/client/to_auto,q_lossless,ret_img,w_735/https://www.thetakeiteasychef.com/wp-content/uploads/2016/07/Burmese-Khow-Suey.jpg',
    categories: ['c1', 'c6', 'c7'],
    ingredients: [
      '500 grams chicken cut to bite-size pieces',
      '300 grams egg noodles',
      '1/2 cup shallots thinly sliced',
      '1/4 cup garlic thinly sliced',
      '3 small red chilies Optional. You can use all green chillies.',
      '2 green chilies slit lengthwise',
      '1 inch ginger grated',
      '500 ml coconut milk',
      '1/2 teaspoon turmeric powder',
      '1 tablespoon gram flour (chickpea flour/besan)',
      '2 sprigs cilantro (coriander leaves)',
      '2 sprigs curry leaves',
      '1 spring onions (preferably scallions/green onions)',
      '1 lime wedges',
      'salt to taste',
      '4 boiled eggs peeled and sliced into halves',
    ],
    steps: [
      'Heat some oil in a pan. When the oil is hot enough, reduce the flame and fry HALF of the thinly sliced garlic.As soon as they start turning brown, scoop them out on to a paper towel to soak up the oil.',
      'Now fry HALF of the thinly sliced shallots. Keep them along with the fried garlic. Leave the oil in the pan.',
      'Add chicken pieces to the pan and start frying them. Add more oil if you have to.Once the chicken starts turning brown, add the curry leaves, grated ginger, and the remaining chopped garlic and sliced shallots.Fry this for 5 minutes while stirring occasionally.',
      'Add the chickpea flour, turmeric powder, and salt.Thinly slice the chillies. I added two green chillies and one red chilli to this mix. Cook for another 5 minutes.',
      'Cook the egg noodles following the instructions on the package.',
      'Drain the noodles, and wash them in cold water. Leave it on a colander to drain the water.',
      'Your curried chicken should be cooked by now with a nice aroma filling up the kitchen.',
      'Add the coconut milk, stir well, and bring to a simmer.',
      'Cook in medium heat. If the temperature goes high, the coconut milk will curdle.',
      'Add salt if required. Switch off.',
      'Serve hot - place some noodles and a sliced egg in a bowl, with some finely chopped cilantro, and pour the curried chicken over it.',
      'Garnish with spring onions',
      'Provide all other accompaniments in small bowls - fried garlic, fried shallots, cilantro, chillies and lime wedges. MUST DO: For the perfect taste, squeeze some lime into your noodle soup just before eating.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: false,
    isVegan: false,
  ),
  Meal(
    id: 'm3',
    title: 'Falooda',
    imgURL:
        'https://images.food52.com/Igtx1TvmHSPWcXYZxsD7Pv2pd-E=/1200x1200/4576da15-f7b5-4896-b36e-42ae437b6a34--2018-0802_sponsored_milk_elixirs-falooda_3x2_julia-gartland_457.jpg',
    categories: ['c1', 'c6', 'c8'],
    ingredients: [
      'Milk 2 cups, full fat',
      'Jelly 1/2 cup, cubed (raspberry or strawberry)',
      'Rose syrup 5-6 tbsps',
      'Falooda seeds 1 tsp (sabja/basil seeds) soak in 1/3 cup water for 20-30 mts',
      'Falooda sev 1/2 cup',
      'Pistachios 5, sliced',
      'ALmonds 4, sliced',
      'Vanilla ice cream 4 scoops',
      'Cherries 2, for garnish',
    ],
    steps: [
      'Bring milk to boil and simmer till it reduces to 1 1/2 cups. Turn off flame and bring to room temperature. Add 1 1/2 to 2 tbsps of rose syrup to the milk and mix. Chill until use.',
      'Make jelly by following the instructions on the packet. Cool and refrigerate. Once cool, cut into small cubes and set aside.',
      'Make falooda sev by following the link provided above. Place in cold water and refrigerate until use.',
      'Soak falooda seeds in water for 30 mts and allow to bloom. Set aside.',
      'Chill the serving glasses in the fridge for half an hour.',
      'To assemble falooda: Take the chilled serving glass and add a generous tbsp of rose syrup or rooh afsa.',
      'Add 2 tbsps of jelly cubes, followed by 2 heaped tbsps of bloomed falooda seeds.',
      'Next layer with 1/4 cup of falooda sev/noodles. Slowly pour the chilled rose milk till 3/4th of the glass. Next add two scoops of vanilla ice cream on top.',
      'Finally drizzle some rose syrup, garnish with sliced nuts and a cherry. Serve immediately to avoid the ice cream from melting and over flowing.',
    ],
    duration: 15,
    complexity: Complexity.challenging,
    isGluton: true,
    isLuctose: false,
    isVegan: false,
  ),
  Meal(
    id: 'm4',
    title: 'Mont Lin Maya ',
    imgURL: 'https://smilesaway.files.wordpress.com/2015/01/hw-myanmar2.jpg',
    categories: ['c1', 'c6', 'c9'],
    ingredients: [
      'Mix rice flour with water',
      'Pinch salt',
      'Pinch MSG*',
      'Pinch sugar',
      'A teaspoon of baking soda',
      'Chopped tips of green onions',
      'Freshly pounded ginger, not too much.',
    ],
    steps: [
      'Mix rice flour, water, sugar, baking soda, salt, ginger and green onions.',
      'Test by putting a bit of mixture on the hot pan, when cooked, if it is too soft, it has too much water, so add some more rice powder.',
      'Leave the mixture, covered for 1 to 2 hours.',
      'Heat the pan, add oil and add the mixture, add a quail egg or a couple boiled butter-beans (pe-pyote).',
      'When the bottom is crispy, turn it and let cook a couple more minutes.',
      'When cooked, place one on top of another one and eat them as a pair.',
    ],
    duration: 60,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm5',
    title: ' Kyar Zan Hin Khar',
    imgURL:
        'https://img.i-scmp.com/cdn-cgi/image/fit=contain,width=1098,format=auto/sites/default/files/styles/1200x800/public/d8/images/methode/2019/11/19/399d0bd8-05f4-11ea-a68f-66ebddf9f136_image_hires_124523.jpg?itok=_GncwaWt&v=1574138728',
    categories: ['c1', 'c6', 'c7', 'c8'],
    ingredients: [
      'Meat as you like (chicken or pork).',
      'Bean stick (pal chaut)',
      'Bean Vermicelli (gouin kar san)',
      'Black Fungus (Hmo chaut)',
      'Pepper powder, salt, chicken powder, fish sauce, chili powder',
      'Onion, ginger, garlic',
    ],
    steps: [
      'Before starting cooking, Bean stick, Bean Vermicelli and Black Fungus are required to put in water at least for 30 minutes.',
      'First, meat should be cooked with onion, garlic, oil, ginger, chili powder, with very few water. It needs to be cooked till no more water. It should be cooked in sauce pan.',
      'Then, you need to boil water in pot. If boiling water, Bean stick and Black Fungus are put into it. After 10 minutes, you can pour the cooked meat into it.',
      'Some salt, chicken powder and fish sauce can be added as you want. After that, you can add Bean Vermicelli into your meal.  After all steps, your pot should be still in fires and it is covered by lip.',
      'After that, you can eat your “kyar san hin khar” eagerly.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm6',
    title: 'Kyet thar kyaw',
    imgURL:
        'https://images.immediate.co.uk/production/volatile/sites/2/2020/08/166_friedchicken_preview-d468e1c.jpg?quality=90&webp=true&resize=975,649',
    categories: ['c1', 'c6', 'c8', 'c9'],
    ingredients: [
      '600g skinless chicken thigh fillets cooked rice, to serve',
      '1 tsp ground turmeric',
      '1 tsp paprika',
      '1 tbsp fish sauce',
      '2 eggs, beaten',
      '75g cornflour',
      '75g rice flour',
      'a good grind black pepper',
      '½ tsp mild chilli powder, (optional)',
      'neutral oil (vegetable, sunflower or peanut), for deep-frying',
      '25g tamarind pulp',
      '1 tbsp palm sugar or soft light brown sugar',
      '2 cloves garlic',
      '½ a thumb-sized piece ginger',
      '1 tsp fish sauce',
    ],
    steps: [
      'Prepare the tamarind by adding 50ml of boiling water to the tamarind pulp in a heatproof bowl and leave for a few minutes. Use a fork to further break up the pulp, then strain through a sieve, discarding any stones, so you are left with the tamarind water.',
      'While the tamarind water is still warm, add the palm sugar and mix until it dissolves.',
      'Crush the garlic, ginger and chilli to a paste using a pestle and mortar, or blitz in a food processor. Add the paste and the fish sauce to the tamarind, mix well and set aside.',
      'Cut the chicken into 2-3cm chunks and mix well with the marinade ingredients in a bowl to coat, then cover and leave to marinate in the fridge for 1 hour.',
      'When ready to fry, assemble a frying station next to the cooker: one bowl containing the beaten eggs, one containing the mixed flours, black pepper, chilli powder and 1/2 tsp of sea salt, and also a plate lined with kitchen paper ready for the cooked chicken.',
      'Heat the oil to a depth of at least 5cm in a wok or deep pan. Test the readiness of the oil with a 1cm piece of bread if it sizzles vigorously and rises to the surface quickly, the oil is hot enough',
      'Take a piece of chicken and dip it in the egg, then dredge it in the flour mixture, ensuring it is covered evenly, and carefully put it in the pan to fry for about 5 minutes. Turn the pieces with heatproof tongs to ensure they cook evenly. Check a piece is cooked by cutting it in half, then scoop out the pieces and transfer them to the plate lined with kitchen paper and cool slightly.',
      'Repeat with the remaining pieces of chicken, but do not overcrowd the pan ',
      'Season with sea salt and serve with the dipping sauce as a snack or with rice as a main.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm7',
    title: 'Yangon htamin paung',
    imgURL:
        'https://i0.wp.com/themoonworld.com/wp-content/uploads/2020/10/20201010_142000-1.jpg?resize=800%2C600&ssl=1',
    categories: ['c1', 'c6', 'c8', 'c9'],
    ingredients: [
      '200g chopped pork',
      '1/4 carrot',
      '1/4 broccoli',
      '10 mushroom',
      '10 boiled quail eggs',
      'a little cabbage',
      'half tofu',
      '1 tablespoon oyster sauce',
      '1 tablespoon chicken powder',
      '1 tablespoon starch',
      '1 tablespoon chopped garlic',
    ],
    steps: [
      'Cut the prepared vegetables. Cut the tofu into dice and boil the quail eggs.',
      'Add water to 1 tablespoon of starch and stir. Then, add water to 1 tablespoon of chicken powder and stir. If you have chicken broth, you do not need to dissolve the chicken powder in water.',
      'Add cooking oil. Then add chopped garlic and fry. Add 200 g of chopped pork and fry together.',
      'Add the slice ​​vegetable and fry. Then, add 1 tablespoon of oyster sauce, the prepared chicken powder melted water, and starch melted water and fry it together.',
      'Add tofu and boiled quail eggs and fry. Slice the onions to eat together and add the Sriracha sauce. And put it on white rice and it done.',
    ],
    duration: 15,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm8',
    title: 'Seafood Curry',
    imgURL:
        'http://linsfood.com/burmese-seafood-curry-recipe/burmese-seafood-curry-blog/',
    categories: ['c1', 'c6', 'c8', 'c9'],
    ingredients: [
      '500 g mixed seafood fish squid, prawns, etc',
      '15-20 live mussels',
      '2 Tbsp fish sauce',
      '2 tsp ground turmeric',
      '1 large onion',
      '2 cloves garlic',
      '2 fresh red chillies',
      '2 Tbsp veg oil',
      '½ tsp chilli powder',
      '1 tsp chilli flakes chilli paste',
      '1 tsp white sugar',
      '1 x 400g can chopped tomatoes',
      '200 ml water',
      'freshly ground black pepper',
      'small handful fresh coriander cilantro',
    ],
    steps: [
      'Marinade the seafood (apart from the mussels) with the fish sauce and turmeric and leave aside while you get all the other ingredients ready.',
      'Scrub the mussels, pull the beard off and set aside. Wash your hands.',
      'Cut the onion into quarters.',
      'Cut the chillies up into 2-3 parts, depending on size.',
      'In a chopper, chop the onion, garlic and chillies to form a paste. You shouldn’t need any water as the onion contains enough moisture.',
      'Using a knife, chop up the fresh coriander and set aside.',
      'Heat the oil in a large wok on medium high heat.',
      'Sauté the onion paste for 2-3 minutes until fragrant.',
      'Add the chilli powder, chilli flakes and sugar and cook for another minute.',
      'Add the tomatoes and three quarters of the water and bring to boil.',
      'Lower the heat right down and simmer, uncovered, for 10 minutes until the sauce has thickened.',
      'Increase the heat, add all the seafood in, including any marinade juice, stir and bring back to boil.',
      'Cover and cook for 5-7 minutes, until your seafood is cooked right through and the mussels have all popped open. I like to cover the wok in this step to ensure that the mussels get steamed.',
      'Check seasoning, adding a little salt if necessary, turn the heat off and stir in a touch of freshly ground black pepper.',
      'Scatter the fresh coriander all over and serve immediately, perfect with some plain rice. But also great with French baguette!',
    ],
    duration: 20,
    complexity: Complexity.challenging,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm9',
    title: 'Chicken Curry',
    imgURL:
        'https://searchingforspice.com/wp-content/uploads/2010/12/Burmese-chicken-curry-900x900.jpg',
    categories: ['c1', 'c6', 'c8', 'c9'],
    ingredients: [
      '580 g chicken diced',
      '4 tomatoes chopped',
      '4 teaspoon lemongrass paste',
      '1 ½ tablespoon fish sauce',
      '1 tablespoon oil',
      '1 teaspoon garam masala',
      '1 teaspoon hot curry powder',
      '½ teaspoon fenugreek',
      '½ teaspoon ground coriander',
      '½ teaspoon cumin',
      '½ teaspoon turmeric',
      '1 onion (large)',
      '2 tablespoon chopped ginger',
      '6 cloves garlic',
      '½ teaspoon cayenne pepper',
      '2 teaspoon paprika',
    ],
    steps: [
      'Mix all the spices together for the marinade.Then rub into the chicken pieces well.Leave to marinate for an hour.',
      'Put all the paste ingredients into a blender and blitz. Add a couple of tablespoons of water',
      'Heat a little oil in a saucepan. Add the paste and fry for about 6-7 minutes. Then add the chicken and cook for another couple of minutes, stirring so it gets sealed on all sides.',
      'Add the tomatoes, lemongrass paste and fish sauce. Stir then add about 200 ml of water. Leave to simmer for about 25 minutes. Stir every so often',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm10',
    title: 'kaw Pyant',
    imgURL:
        'https://media-cdn.tripadvisor.com/media/photo-s/0a/ca/30/45/kaw-pyant.jpg',
    categories: ['c1', 'c6', 'c8', 'c7'],
    ingredients: [
      '15 spring roll rice paper wrappers (about 8 inches/20cm in diameter)',
      '8 tablespoons dried shrimp',
      '4 eggs',
      '2 cloves garlic , chopped',
      '3 carrots , peeled and cut in julienne',
      '1 lb jicama (frozen or fresh), grated',
      'A few lettuce leaves',
      '3 tablespoons nuoc mam (fish sauce)',
      '4 Chinese sausages , thinly sliced',
      '7 tablespoons hoisin sauce (Asian barbecue sauce)',
      '3 teaspoons crushed sesame seeds (or roasted peanuts), according to taste',
      'Vegetable oil',
    ],
    steps: [
      'Heat 3 tablespoons of oil in a wok over medium heat, then add the carrots and the jicama.',
      'Mix well and sauté for a minute.',
      'Add the fish sauce. Mix well.',
      'After 5 minutes, the vegetables will be cooked but still crisp. Set aside.',
      'In another wok, heat 2 tablespoons of oil over high heat and sauté the garlic clove for a few seconds, then lightly brown the dried shrimp. Set aside.',
      'In a frying pan, pour 1 tablespoon of oil and over very low, heat the sausages for 10 minutes.',
      'Finally, in a bowl, beat the two eggs, and season with salt and pepper.',
      'Heat 3 tablespoons oil in a pan and cook the eggs in a thin omelette. Cool and cut into large slices.',
      'Then prepare the sauce by mixing 1 tablespoon warm water and the hoisin sauce in a bowl.',
      'Sprinkle with golden sesame (or roasted peanuts). Set aside.',
      'Heat (without boiling) a large amount of water to moisten the rice paper wrappers.',
      'Pour this water into a large bowl.',
      'Dip a wrapper for 5 seconds in the hot water and gently place it flat on a cloth.',
      'Place the ingredients in the middle, towards the edge of the wrapper, starting with a small leave of lettuce, then the vegetables then the shrimps and 1 to 2 slices of omelette.',
      'Roll the wrapper by pressing on the ingredients.',
      'Before closing, place sausage slices to make them visible, fold the edges of the roll, and continue to roll to close it properly.',
      'Serve with reserved sauce.',
    ],
    duration: 60,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm11',
    title: 'Sushi',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS57Q6Wm8jwJI5oli6y7Y262jProBTbcdPUjg&usqp=CAU',
    categories: ['c2', 'c6', 'c7', 'c8', 'c9'],
    ingredients: [
      '1 ⅓ cups water',
      '⅔ cup uncooked short-grain white rice',
      '3 tablespoons rice vinegar',
      '3 tablespoons white sugar',
      '1 ½ teaspoons salt',
      '4 sheets nori seaweed sheets',
      '½ pound imitation crabmeat, flaked',
      '1 avocado - peeled, pitted, and sliced',
      '½ cucumber, peeled, cut into small strips',
      '2 tablespoons pickled ginger',
    ],
    steps: [
      'Preheat the oven to 300 degrees F (150 degrees C).',
      'Bring water to a boil in a medium pot; stir in rice. Reduce heat to medium-low, cover, and simmer until rice is tender and water has been absorbed, 20 to 25 minutes..',
      'Mix rice vinegar, sugar, and salt in a small bowl. Gently stir into cooked rice in the pot and set aside.',
      'Lay nori sheets on a baking sheet.',
      'Heat nori in the preheated oven until warm, 1 to 2 minutes.',
      'Center 1 nori sheet on a bamboo sushi mat. Use wet hands to spread a thin layer of rice on top. Arrange 1/4 of the crabmeat, avocado, cucumber, and pickled ginger over rice in a line down the center. Lift one end of the mat and roll it tightly over filling to make a complete roll. Repeat with remaining ingredients.'
          'Use a wet, sharp knife to cut each roll into 4 to 6 slices.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm12',
    title: 'Sashimi',
    imgURL:
        'https://www.japanesecooking101.com/wp-content/uploads/2019/08/DSC00528b-1140x640.jpg',
    categories: ['c2', 'c6', 'c9', 'c8'],
    ingredients: [
      'Daikon radish about 4″ (10 cm)',
      'tuna Sashimi grade, block',
      'yellowtail Sashimi grade, fillet',
      'salmon Sashimi grade, block',
      'Shiso leaves',
      'Wasabi',
      'Soy Sauce',
    ],
    steps: [
      ' Remove skin of Daikon radish. Slice thinly with a mandolin or slicer. Stack 3-4 layers of thin Daikon, and julienne very thinly. Put it in a bowl of water and leave for 15 minutes to make it crispy. Strain and remove moisture.',
      ' Slice tuna and yellowtail into 1/4″-1/3″ thick (6 mm-8 mm) pieces. Slice salmon thinly at a slight angle.',
      'Serve Sashimi on a plate with radish, Shiso leaves, and Wasabi along with Soy Sauce for dipping.',
    ],
    duration: 30,
    complexity: Complexity.challenging,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm13',
    title: 'Okonomiyaki',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8-n_urOpEu8BAq3AH7Er7OdD51tzcp-QDdw&usqp=CAU',
    categories: ['c2', 'c7', 'c6', 'c8'],
    ingredients: [
      '100g okonomiyaki flour',
      '100ml water',
      '1 egg',
      '¼ cabbage',
      ' spring onion',
      'Oil for frying',
      'Any meat or seafood of your choice.',
      'For a vegetarian option, you can use firm, smoked or deep fried tofu or tempeh bacon.',
      'Mayonnaise',
      'Okonomiyaki sauce',
    ],
    steps: [
      'Whisk together the okonomiyaki flour (or flour + baking powder + soy sauce/dashi powder) and water. To make the batter fluffier you can refrigerate for 1-8 hours to let the gluten rest. However, even if you don’t, the okonomiyaki will still taste good.',
      'Finely chop the cabbage and spring onion. Add the chopped vegetables to the batter.',
      'Mix the egg into the batter, being careful not to over mix, or the final okonomiyaki will be too chewy and tough.',
      'Thinly slice your protein and set aside.',
      'Heat the oil in a large frying pan or griddle, on medium heat.',
      'Once the pan is hot, add a circle of batter to the pan. The okonomiyaki pancake should be about 2cm thick, but can be made thinner to make cooking easier.',
      'Add the slices of protein on top of the okonomiyaki and cover with a lid. Cook for about 5 minutes covered.',
      'After the bottom of the pancake is browned, flip it over and cook covered for another 5 minutes.',
      'Flip a third time and cook uncovered for 2 minutes.',
      'Take off the heat, plate and add toppings of your choice: mayonnaise, okonomiyaki sauce etc.',
    ],
    duration: 60,
    complexity: Complexity.challenging,
    isGluton: false,
    isLuctose: false,
    isVegan: true,
  ),
  Meal(
    id: 'm14',
    title: 'Takoyaki',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJDarEwOxu-kSFFnecHkZwtNlwH9zPjCVz8g&usqp=CAU',
    categories: ['c2', 'c9', 'c6'],
    ingredients: [
      '2 cups Dashi 480ml',
      '2 eggs',
      '1/4 tsp salt',
      '1 cup plus 2 Tbsp all purpose flour ',
      '2-3 green onions finely chopped',
      '2 Tbsp Benishoga pickled red ginger, chopped',
      'Boiled octopus* cut into 1/2″ cubes',
      'oil',
      'Takoyaki sauce or Okonomiyaki sauce',
      'mayo',
      'Aonori green dried seaweed',
      'Katsuobushi dried bonito flakes',
      'Substitute octopus with sausage cheese, ham, and etc',
    ],
    steps: [
      'In a large bowl, mix well Dashi, eggs, soy sauce, salt, and flour with a whisk.',
      'Heat a Takoyaki pan with oil to very hot, just until the oil begins to smoke. Use enough oil to coat the pan using a paper towel so that the batter won’t stick. Then pour batter to fill the holes of the pan.',
      'Drop octopus pieces in the batter in each hole, and sprinkle chopped green onions and ginger all over the pan.',
      'Cook at medium heat for 1-2 minutes and turn over using a Takoyaki turner (you can use a chopstick too). It can be a little tricky at first, so watch the video to see the technique. Cook another 3-4 minutes, turning constantly.',
      'Place the cooked Takoyaki on a plate and pour Takoyaki sauce and mayo over them (to taste). Finish the dish by sprinkling the Takoyaki with Aonori (green dried seaweed) and Katsuobushi (dried bonito flakes).',
    ],
    duration: 25,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: false,
    isVegan: false,
  ),
  Meal(
    id: 'm15',
    title: 'Oden',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpNtJ1qLAi8r8E7RSuvE0ECM3jo6bEktsBCA&usqp=CAU',
    categories: ['c2', 'c7', 'c8', 'c6', 'c9'],
    ingredients: [
      '3 cups homemade dashi',
      '1/2 cup water',
      '2 softened kombu strips',
      '12 oz. Japanese oden fish cakes and fish balls',
      '2 hard-boiled eggs',
      '6 oz. daikon',
      '2 oz. konnyaku',
      ' tablespoon soy sauce',
      '2 tablespoons mirin',
      '1 tablespoon cooking sake',
      'Japanese Togarashi (Japanese 7-Spice Blend )',
      'Japanese mustard (Karashi, for serving)',
    ],
    steps: [
      'Rinse the fish cakes and fish balls with running water, remove the excess oil from the fish cakes and fish balls. Drained, pat dry with paper towels and set aside.',
      'In a soup pot, bring the dashi, water, kombu strips (if using) to boil. Add the daikon and stew on low heat until they are cooked through.',
      'Add the hard-boiled eggs, konnyaku (if using) and fish cakes. Add the soy sauce, mirin and sake. Turn the heat to low and simmer for 15 minutes. Serve the oden warm with Japanese mustard and Togarashi .',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm16',
    title: 'Natto',
    imgURL:
        ' https://cdn.britannica.com/16/236016-050-757D6F7E/natto-fermented-soybeans-rice-green-onions-raw-egg.jpg',
    categories: ['c2', 'c7', 'c6', 'c8'],
    ingredients: [
      '2 cups soybeans',
      '3 Tbs. water, boiled for 5 to 10 minutes to sterilize',
      '1 packet Natto Starter Culture',
    ],
    steps: [
      ' Wash the soybeans and soak in 6 cups of water for 9 to 12 hours (longer soaking time recommended for colder months) to get them ready for fermentation.',
      'Drain the soybeans from the soaking water. Place beans in a large pot, fill with water and boil for 2-3 hours, checking every half hour or so. You want them to be tender but not mushy so that the spores have plenty of moisture for fermentation, but the final result is still firmly textured.',
      ' Rinse or dunk a colander, cooking spoon, and casserole dish with boiling water to sterilize. We want to make sure that only the right organisms thrive in our fermented soybeans.',
      'In the sterilized colander, drain the cooked beans and place in the sterilized casserole dish. Turn oven light on so it preheats to 100 degrees F.',
      'Stir in the natto powder with 3 Tbs. boiled and cooled (for sterilization) water. While the beans are still warm, pour the natto spore packet over the beans. Stir the beans carefully using the sterilized spoon.',
      'Spread the beans in a ~1 inch layer in the casserole dish. If at any point in the process the beans spill on the counter, etc., discard those beans',
      'Tightly cover the casseroled dish with aluminum foil. Poke pin holes in the foil, placed 1" apart. The natto spores need a little oxygen and darkness for idea growing conditions.',
      'Place the covered casserole dish in the oven, dehydrator, or other warmer and allow the natto to ferment for 22 to 24 hours, being sure to keep the temperature at a steady 100 degrees F. When you see a whitish film and smell an ammonia-like aroma coming from the beans,',
      'When finished, let the Japanese natto cool at room temperature for 2 hours. Remove aluminum foil and store in covered containers in the refrigerator at least overnight for best flavor and stringiness. Your natto will last for about a week in the refrigerator.',
    ],
    duration: 48,
    complexity: Complexity.hard,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm17',
    title: 'Sake',
    imgURL:
        ' https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/34/2019/11/Sake-Unsplash.gif',
    categories: ['c2', 'c7', 'c8', 'c6'],
    ingredients: [
      '2.5 pounds rice (husked or raw)',
      '1/2 pint grape concentrate or 1 pound of light raisins',
      '1 gallon hot water',
      '2.5 pounds corn sugar or honey',
      '3 teaspoons acid blend',
      '3/4 teaspoon yeast energizer',
      '1 Campden tablet',
      '1 package red star champagne yeast',
    ],
    steps: [
      ' Wash and coarsely crush rice.',
      'Place rice and chopped raisins in nylon straining bag, tie top, and place in sanitized primary fermentation container.',
      'Pour hot water over rice and stir in all ingredients except yeast and nutrient. Don’t forget the grape concentrate if not using raisins .',
      'Wait 48 hours.',
      'Add yeast and energizer and cover primary fermenter with a cheesecloth.',
      'Stir daily, checking specific gravity and pressing pulp lightly. For more information on taking gravity readings, check out this post.',
      'When gravity reaches 1.050 (after 2-3 days), add 1/4 pound of dissolved sugar or honey per gallon.',
      'When gravity drops to 1.030 (after 6-7 days), strain juice from bag.',
      'Siphon wine into secondary fermentation container and attach bung and  airlock.',
      'At a specific gravity (SG) of 1.020, add another 1/4 pound of dissolved sugar or honey per gallon.',
      'When fermentation is complete (at a SG of 1.010 or less), siphon off into a sanitized secondary container and attach airlock.',
      'Siphon every 2 months to aid in clearing.',
      'Bottle when fermentation ceases or when ready.',
      'It is possible to continue building up alcohol by adding additional sugar until fermentation ceases. For a sweeter sake, add 1/2 teaspoon of stabilizer and 1/4 pound dissolved sugar, per gallon, before bottling.',
    ],
    duration: 1440,
    complexity: Complexity.hard,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm18',
    title: 'Dango',
    imgURL:
        'https://www.chopstickchronicles.com/wp-content/uploads/2017/11/Hanami-Dango-22.jpg',
    categories: ['c2', 'c8', 'c6'],
    ingredients: [
      '8 oz Mochiko',
      '8 oz Tofu soft',
      '2 Tbsp Katakuriko (potato starch) or corn starch',
      '1/2 cup sugar',
      '4 Tbsp Soy Sauce',
      '1 cup water 240ml',
    ],
    steps: [
      'In a bowl, mix Tofu and Mochiko well. The dough should not be too loose nor too firm (about the firmness of an earlobe) .',
      'Scoop out tablespoon-size portions of dough and roll into balls.',
      'Boil water in a large pot, and cook the dough balls until they float. Once they float in the boiling water, cook 2-3 minutes longer, then remove from the water using a mesh strainer (or ladle) and place onto a plate lined with a paper towel .',
      'Meanwhile, make Mitarashi sauce. In a small pot, add all the ingredients for the sauce and stir. Cook until the sauce boils and keep it warm.',
      'Slide 3-4 Dango balls onto each skewer. Heat a non-stick frying pan at medium heat, place skewered Dango in the pan, and cook until lightly browned.',
      'Put Dango on a plate and pour the sauce to coat .',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm19',
    title: 'japanese Curry',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA9xOC6ilstOqo7YRLtpvFXGYjRVbVCxcenglEjCHzdHAF4R3O5F8iqxy2TYO01NZtOLc&usqp=CAU',
    categories: ['c2', 'c7', 'c8', 'c9', 'c6'],
    ingredients: [
      'Beef (or Chicken, Lamb, Shrimp), chopped	450 g / 1 lb',
      'Medium Onions, minced	1 3/4 (350 g / 13 oz)',
      'Medium Carrot, chopped	1/2 (100 g / 3.5 oz)',
      'Medium Potato, chopped	1 (150 g / 5 oz) ',
      'Vegetable oil	1 Tbsp',
      'Water	540 ml',
      'S&B Golden Curry Sauce Mix 92g	1 pack',
    ],
    steps: [
      'Stir-fry meat and vegetables with oil in a large skillet on medium heat for approx. 5 min.',
      'Add water and bring to boil. Reduce heat, cover and simmer until ingredients are tender, approx. 15min.',
      'Turn the heat off, break S&B Golden Curry Sauce Mix into pieces and add them to the skillet. Stir until sauce mixes are completely melted. Simmer approx. 5 min., stirring constantly.',
      'Serve hot over rice or noodles .',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm20',
    title: 'Dorayaki',
    imgURL:
        'https://www.honestfoodtalks.com/wp-content/uploads/2022/02/2-Dorayaki-with-red-bean-filling.jpg',
    categories: ['c2', 'c6', 'c7', 'c8'],
    ingredients: [
      '2 medium egg',
      '80 g sugar',
      '1 tbsp honey',
      '120 g cake flour ',
      '½ tsp baking soda',
      '50 ml water',
      'cooking oil - for frying - flavorless oil like vegetable or canola works best',
      '300 g red bean paste - about 2 tbsp per pancake',
    ],
    steps: [
      'Start heating the pan on a low heat for about 10 minutes before you plan to start. This will make the heat even on the pan.',
      'Add a small amount of cooking oil to the pan and use kitchen paper to spread it all over the pan and remove any excess. This will give the dorayaki a clean, smooth surface without any spots.',
      'Take the jug from the refrigerator and pour the batter into the pan. When pouring, pour the batter in one spot and allow it to spread out, the size should be about 8cm (about 3 inches) in diameter.',
      'Cook for about 1 ½ to 2 minutes or until you see bubbles forming on the top.',
      'Once flipped, cook on the other side for about 1 minute and remove from the pan .',
      'Place a plain pancake on top of each one that has red bean paste. Lightly press around the edges to close the dorayaki .',
    ],
    duration: 45,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm21',
    title: 'STEAMED FISH',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs65FtTRrY0dFXgml1E-6hE5ok9m7O-CKhuQ&usqp=CAU',
    categories: ['c3', 'c7', 'c8', 'c9', 'c6'],
    ingredients: [
      '2 scallions',
      '2 tablespoons ginger',
      '1 small bunch cilantro',
      '1 ½ tablespoons light soy sauce (or seasoned soy sauce)',
      '1/8 teaspoon salt',
      '1/8 teaspoon sugar',
      '2 tablespoons hot water',
      '10 ounce fillet of delicate white fish (such as sea bass, grey sole, flounder, fluke, tilapia, or haddock)',
      '2 tablespoons vegetable oil',
    ],
    steps: [
      'Cut the scallions into 2-inch lengths, and cut the pieces in half lengthwise. Julienne them thinly. Thinly slice about 15g of ginger, and julienne them. Give the cilantro a rough chop. Set the aromatics aside.',
      'Combine the light soy sauce, salt, sugar and hot water in a small bowl and mix until the sugar and salt are dissolved. Set aside.',
      'Prepare your steaming set-up, and fill with 1-2 inches of water. Bring to a boil.',
      'Rinse your fish fillet, and carefully lay it on an oblong heat-proof plate that will fit into your wok or steaming setup. Carefully place it in the steamer, and adjust the heat to medium. The water should be at a slow boil that generates a good amount of steam, but not so high that the water evaporates too quickly.',
      'Cover and steam for 7-10 minutes depending upon the size and thickness of your fish fillet. If you have extremely small, thin fillets (half an inch), cook for 4-5 minutes. Check for doneness using a butter knife. If it falls easily through the thickest part of the fillet to the bottom of the plate, the fish is done.',
      'Turn off the heat, and carefully drain any liquid on the plate. Spread about ⅓ of the scallions, ginger, and cilantro on the steamed fish (alternatively, you can wait to do this AFTER adding the sauce).',
      'To make the sauce, heat a wok or small saucepan to medium high heat, and add 2 tablespoons vegetable oil. Add the remaining ⅔ of the ginger, and fry for 1 minute. Add the white parts of the scallions and cook for 30 seconds.Then add rest of the scallions and cilantro. The mixture should be sizzling.',
      'Add the soy sauce mixture. Bring the mixture to a bubble, and cook until the scallions and cilantro are just wilted, about 30 seconds.',
      'Pour this mixture over the fish. If you prefer to add the raw aromatics after adding the sauce, you can do so now, and heat an additional 1 tablespoon of vegetable oil to pour over the raw aromatics. Serve immediately.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm22',
    title: 'Fried Milk',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0O6lzA0oD00RxcVo_aayqrULh5uekqLOeFA&usqp=CAU',
    categories: ['c3', 'c7', 'c8'],
    ingredients: [
      '1 cup coconut milk',
      '¼ cup milk',
      '3 tbsp. cornstarch',
      '3 tbsp. sugar',
      '2 large eggs, whisked well for coating',
      '¼ cup cornstarch for coating',
      '1 cup breadcrumbs or oats',
      'Oil for deep-frying',
    ],
    steps: [
      'In a small bow, add coconut milk, milk, cornstarch and sugar. Heat over slowest fire and until heating until thickened. In the process, stir in one direction.',
      'Transfer to a square baking pan and set aside to cool down in fridge. Transfer out and cut into small strips around 5 cm long and 3 cm wide.',
      'oat with starch, egg and breadcrumbs in sequence.',
      'Heat oil to 160 degree C. Place 4-5 pieces on a flat strainer, dip the strainer in and fry until slightly golden brown and crispy.  Repeat until all of the remaining pieces are fried. Remove extra oil with kitchen paper and serve directly.',
      'Absorb extra oil with kitchen paper and serve hot.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: false,
    isVegan: false,
  ),
  Meal(
    id: 'm23',
    title: 'Mapo Tofu Recipe',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrbkrJpzaHVwCvtA-EbW-X1_r74QK2qYzTfA&usqp=CAU',
    categories: ['c3', 'c7', 'c8', 'c9'],
    ingredients: [
      '450 g soft tofu',
      '100 g minced meat-beef or pork',
      '½ tbsp. sesame oil',
      '½ tsp. salt',
      '3 tbsp. cooking oil',
      '1.5 tbsp. Doubanjiang ,roughly chopped',
      '½ tbsp. fermented black beans ,also known as dou-chi and fermented soya beans, roughly chopped',
      '1 tbsp. pepper flakes or powder ,optional',
      'water or broth for braising',
      '1 tbsp. light soy sauce',
      '1 tsp. sugar ,optional for reducing the spiciness',
      '2 scallion whites ,finely chopped',
      '4 garlic greens or scallion greens ,finely chopped',
      '2 garlic cloves ,finely chopped',
      '5 ginger slices ,finely minced (around 1 teaspoon)',
      '½ tbsp. Sichuan pepper for making fresh ground powder',
      '2 and ½ tablespoon water',
      '1 tablespoon cornstarch',
    ],
    steps: [
      'Add a small pinch of salt and ground pepper in minced beef or pork. Mix well and set aside.',
      'Cut tofu into square cubes (around 2cms). Bring a large amount of water to a boil and then add a pinch of salt. Slide the tofu in and cook for 1 minute. Move out and drain. This helps to remove the raw soy flavor form tofu.',
      'Get a wok and heat up around 2 tablespoons of oil, fry the minced meat until crispy. Transfer out and leave the oil in.',
      'Add another 1 tablespoon of vegetable cooking oil and fry doubanjiang for 1 minute over slow fire until the red turns red (bring us a lovely red color dish) and add fermented black beans,  garlic, scallion white and ginger, cook for 30 seconds until aroma. Optionally mix pepper flakes in. Pepper flakes should be added at the end because it contains little water and can be burnt easily.',
      'Pour in water or stock. Add light soy sauce, sugar and half of the cooked beef (providing more flavors to the soup) after the broth boils and let it continue simmering for 2-3 minutes. Place the tofu in, simmer for another 6-8 minutes. The longer time of simmering helps the tofu to absorb the flavors.',
      'During the process of simmering, mix 1 tablespoon of cornstarch with 2.5 tablespoons of water in a small bowl to make water starch. Stir the water starch and then pour half of the mixture to the simmering pot. Back push and wait for around 30 seconds and then pour the other half. You can slightly taste the tofu and add pinch of salt if not salty enough.  Add cooked beef to creates some crispy texture and then drizzle sesame oil. Mix well.',
      'Transfer out when almost all the seasonings stick to tofu cubes. Sprinkle Szechuan peppercorn powder (to taste)and chopped garlic greens if using.',
      'Serve immediately with steamed rice.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm24',
    title: 'Stir Fry',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx5FB5IWb_TvS6tZfOtUPKs4PgcxnlV3cytg&usqp=CAU',
    categories: ['c3', 'c7', 'c8'],
    ingredients: [
      '200 g pork butt or tenderloin , thinly sliced',
      '¼ tsp. salt , optional (you can skip this for a less salted dish)',
      '½ tbsp. cooking wine',
      '½ tbsp. oyster sauce',
      '2 tbsp. water or chicken stock',
      '¼ tsp. white pepper',
      '3 tsp. cornstarch',
      '½ tbsp. vegetable oil',
      'cooking oil as needed',
      '½ thumb ginger ,skin removed and sliced',
      '1 garlic cloves ,sliced',
      '10 fresh shiitake mushrooms ,remove the roots and sliced',
      '4 scallions ,cut into small sections white part and green part separated',
      '½ tbsp. oyster sauce',
      '½ tbsp. light soy sauce',
      '1 tsp. sesame oil , optional',
    ],
    steps: [
      'Thinly slice the pork. Add salt (or skip the salt if you want a less salted dish), Shaoxing wine, oyster sauce, and white pepper. Mix well.',
      'Add water or stock in. Grasp the pork slice for 2-3 minutes until all the juice is well absorbed, then add cornstarch.  Set aside for 15minutes. Mix in around ½ tablespoon of vegetable cooking just before frying.',
      'Heat your wok or pan first. Add cooking oil to form a 2-3 cm high layer (do not be scared by the oil amount, we do not eat them all). Spread the pork sliced in when the oil begins to warm but not hot. Let them stay for around 3-5 seconds and then quickly fry them until turns pale. Transfer out immediately.',
      'Remove the extra oil and save them for vegetable stir fries. Keep around 1 tablespoon of oil and fry garlic, ginger and scallion until aromatic. Place shiitake mushroom in, add oyster sauce and light soy sauce. Fry for around 30 seconds until the shiitake mushrooms are just cooked.',
      'Return pork and add scallion sections, drizzle sesame oil. Quickly mix well and transfer out. Serve hot.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm25',
    title: 'Scallion Pancakes',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKFZ_2_NNEkzeQIbcaTBO9Yt8sB-iIyd0VRA&usqp=CAU',
    categories: ['c3', 'c6', 'c7', 'c8'],
    ingredients: [
      '2 cup unshifted all purpose flour , around 300g',
      '½ cup hot boiling water',
      '¼ cup room temperature water',
      '1 tsp. salt',
      '1 tbsp. vegetable cooking oil',
      '4~6 tbsp. cooking oil , 2 for brushing, other for pan-frying',
      '2 cup chopped scallion , use green part only',
      '1 tbsp. Chinese five spice powder , optional',
      '1 tbsp. light soy sauce',
      '½ tbsp. sesame oil',
      '¼ tsp. salt',
      '1 tbsp. chili oil',
      'chopped green onion and coriander',
    ],
    steps: [
      'Mix salt with all purpose flour.',
      'Stir in the hot water first. Mix for a while and then stir in the room-temperature water and cooking oil too. Grasp everything to form a ball, cover, and rest for 10 minutes.',
      'After resting, then knead until very smooth (around 3-5 minutes ). Then divide the dough into 4 pieces. Shape each portion into a smooth round dough. Cover the rest for 20 to 30 minutes.',
      'Take one small ball out, and roll it out to a rectangle around 10cm wide and 8cm high. Brush some oil in the center part and then sprinkle Chinese five spice powder if using. Spread the chopped scallion in. Fold up the rectangle into a cylinder. Repeat to finish all four cylinders.',
      'Take one out, slightly lengthening the cylinder with two hands, and then roll from one end to the other to form a snail shape. Suck the end into the dough.',
      'Repeat to finish all four. Remember to cover to avoid drying out.',
      'Then roll out the pancake into a large round circle. Be gentle and use your hand as most as possible. To get a perfect round pancake for beginners, get yourself a small pan (18 to 20cm in diameter) and push with your fingers to spread the dough over the pan.',
      'Pour around 2 tablespoon of oil in a pan and then place one pancake in.',
      'Use middle fire to pan-fry until the surface becomes brown around 2-3 minutes. And turn over to fry for another 1 to 2 minutes. Use a spatula to twirl the circle from time and time especially the central part to ensure the circle is evenly fried. You can serve it as a whole or cut it into small pieces.',
      'Mix all the seasonings for the dipping sauce. Serve along with the pancakes.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm26',
    title: 'HONG SHAO ROU',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMXB3j80jCqo8HoK5prRmdoiCzdPN8izbCAw&usqp=CAU',
    categories: ['c3', 'c7', 'c8', 'c9'],
    ingredients: [
      '500 g pork belly , cut into cubes around 2 inches',
      '1tbsp. cooking wine',
      '1 piece ginger , smashed',
      '4 scallion sections',
      '10 Sichuan peppercorns , optional',
      '¼ cup yellow rock sugar , broken if you have large pieces',
      '3 tbsp. light soy sauce',
      '2 scallions , cut into sections',
      '4 green onions , 1 finely chopped for garnish and the left into long sections',
      'hot water to cover the pork cubes , as needed',
      '¼ tbsp. black vinegar or apple vinegar , optional',
    ],
    steps: [
      'Heat wok or pan until hot, then place the pork belly in, skin downside. Use hand to move the skin on the surface of the wok until the skin is almost seared.',
      'Wash carefully to clean the seared part completely. Then cut the pork belly into 2 cm cubes.',
      'In a large pot with enough water, place the pork belly cubes in. Add scallion, smashed ginger, cooking wine and Sichuan peppercorn. I highly recommend you trying to use Sichuan peppercorn in the process of blanching meat, it is such an odd taste killer. Bring to a boiling and then continue cook for 5 minutes. Transfer the pork belly out and wash if necessary. I wash it in the boiling water in the video. Set aside and drain.',
      'Pour in hot water to cover the pork belly, add light soy sauce, scallion and smashed ginger. Cover and simmer for 1 hour using middle fire. Check the softness at the stage.',
      'Then turn up the fire, remove the lid and thicken the sauce. Pick up and discard scallion and ginger. They have finished their tasks. Optionally but highly recommend adding around ½ tablespoon of black vinegar or lemon juice in. This add extra aroma. No sour taste at the final dish.',
      'Once most of the liquid is gone, slow down the fire. Continue pushing and moving the pork cubes to avoid over-heating partially in the last minutes. It is done when pork belly is well colored and the oil at the bottom begins to turn transparent. Serve hot with scallions sprinkled.',
    ],
    duration: 48,
    complexity: Complexity.challenging,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm27',
    title: 'Crispy Eggplants',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVVSTxCKs-OsgS9acnx7yLMvQsHUbjkX3XgPfMCHSiD2YHT9ueFkToEhiregPeMuZRpYg&usqp=CAU',
    categories: ['c3', 'c6', 'c7', 'c8', 'c9'],
    ingredients: [
      '1 eggplant , cut into wedges by rotating',
      'coriander stem , cut into sections',
      '1 cup potato starch , or potato starch',
      '4 tbsp. vegetable cooking oil',
      '1 tsp. sugar',
      'dash of white pepper',
      '2 tbsp. light soy sauce',
      '1 tbsp. black vinegar',
      '1 tbsp. oyster sauce',
      '½ thumb ginger , shredded',
      '2 cloves garlic , shredded',
      '1 scallion , cut into sections',
      '5 dried chili pepper , cut into shreds too',
      '1 tsp. Sichuan peppercorn',
    ],
    steps: [
      'Cut the eggplants into 2 cm widgets. Here is the tip of cutting widgets, cut a triangle area off the eggplant, rotate the eggplants and continue to cut the next wedges. If you are not familiar with this cutting method, simply cut strips.',
      'Add around 1 teaspoon of salt in a large pot of water and then soak the eggplant in the salty water. Absorbing some water can shorten the time of cooking and we can guarantee the eggplants are well cooked in short deep frying process. This also helps to attach the starch in the next step.',
      'Add starch (cornstarch or potato starch) by batches and make sure each piece of the eggplants is well coated by starch. I highly recommend using potato starch for this dish because it gives a lovely white and crispy shell.',
      'When the eggplant is ready, shred ginger, garlic and dried chili peppers. Then cut coriander stem into sections too if using. Then whisk all the ingredients for the bowl sauce together in a small bowl.',
      'Add around 4 tablespoon of oil in wok and shallow fry the eggplant widgets until slightly golden brown. Fry the eggplant widgets for two batches and try to leave some space among each widgets because they may stick together at the very beginning. But if this happens.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm28',
    title: 'Pot Stickers',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7EkQoH1gUE393hii0UZPnDsXFwU02tQCcCg&usqp=CAU',
    categories: ['c3', 'c6', 'c7', 'c8'],
    ingredients: [
      '250g minced pork (with some fat)',
      '300g to 500g Chinese chives (remove the hard ends)',
      '1 egg',
      '1 tbsp. cooking wine',
      '½ tsp. white pepper',
      '1 tbsp. light soy sauce',
      '1 tbsp. oyster sauce',
      '2 tbsp. hot oil',
      '¼ cup chopped scallion',
      '2 tsp. sesame oil',
    ],
    steps: [
      'In a mixing bowl, add ground pork, a small pinch of salt, ginger, egg, light soy sauce, white pepper, and then oyster sauce. Mix well.',
      'Then place the green onion on top and drizzle hot oil on green onions. This helps to improve the aroma of the green onion.',
      'Stir the filling in one direction for 2-3 minutes until getting a paste texture and the filling becomes quite sticky and lighter in color. Set aside for 1 hour or cover with plastic wrapper and overnight if you are not in a hurry.',
      'Finely chop chives and mix with 2 tablespoons of sesame oil or other vegetable oil. Mix chive with pork before wrapping.',
      'spoon around 1 tablespoon of filling and put in the middle of the wrapper in the left hand. Moisten one edge with some water so that the edges can be pressed firmly.',
      'fold one side of the wrapper against the other. Press the center together.',
      'began to make the pleats on one side.',
      'finish the other side.',
      'Pan-frying process: Add oil in a pan and lay the dumplings. Fry over medium fire until the bottom is golden brown.',
      'To make the dumplings even crisper, turn the dumplings over and fry the pleats side until slightly browned.',
      'Swirl around ¼ cup of water and then cover the lid immediately. Continue heating until all of the water is evaporated.',
      'Then all of the water is evaporated, continue cooking for a while until the shell becomes crispy again.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm29',
    title: 'Chinese Salted Duck',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3UhK_vZdKT5g0dSaG1Gdx-aAlQv8PSYIXIw&usqp=CAU',
    categories: ['c3', 'c7', 'c8', 'c9'],
    ingredients: [
      '1 duck , around 3000g',
      '4 tbsp. salt',
      '2 star anise',
      '1 tbsp. Sichuan peppercorn',
      '2 scallion',
      '1 thumb ginger smashed',
      '1 tbsp. ShaoXing cooking wine',
    ],
    steps: [
      'Clean the duck under running water and remove any giblets and hair. Then pat dry with kitchen paper. Then poke some hole on the surface of the duck so the flavors can go insider easier.',
      'In a pan, add 4 tablespoons of salt, 1 tablespoon of Sichuan peppercorn and 2 star anises. Stir fry over slow fire until aromatic and the salt becomes slightly browned. Set aside to cool down.',
      'Rub the salt on every part of the duck. Then cover with plastic wrap, place in fridge and set aside for 1 day.',
      'Add enough water in a large pot (the water level should cover the duck), add ginger, scallion and ShaoXing wine. Heat to bring the content to a boiling. Place the duck in, the water temperature drops in time. Then slow the fire to keep the broth slightly simmering but not boiling. Don’t cover the lid and cook for 10 minutes.',
      'Cover the lid now, turn off the fire and soak the duck for another 20 minutes. Then start the fire and continue heating until the water boils. Turn off fire and let it soak for another 20 minutes in the broth.',
      'Transfer the duck to cutting board. Cut into pieces and server directly or with any dipping sauce you prefer. But the duck itself is good enough.',
    ],
    duration: 48,
    complexity: Complexity.challenging,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm30',
    title: 'Chinese Pork Bun',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXR1qAO-Up7fqUANITXTWWS84xQbVleUK3EQ&usqp=CAU',
    categories: ['c3', 'c6', 'c7', 'c8'],
    ingredients: [
      '2 cup all-purpose flour , ½ cup more for dusting',
      '1.5 tsp. instant yeast',
      '150 ml water',
      '2 cup ground pork',
      '2 cup finely chopped carrots',
      '1 cup finely chopped celery , optional',
      '2 garlic cloves , finely chopped',
      '2 tbsp. of cooking oil',
      'pinch of salt',
      '1 tsp. sesame oil',
      'pinch of salt',
      '1 tbsp. oyster sauce',
      '1 tbsp. light soy sauce',
      '¼ tsp. Chinese five spice powder',
      '½ tbsp. finely chopped ginger',
    ],
    steps: [
      'Add yeast to water (cold water in summer and warm water in winter). Wait for around 10 minutes until the yeast is well activated.',
      'Stir the yeast water with flour. Grasp everything together and knead until the dough becomes smooth and elastic.',
      'Brush some oil on a large bowl and transfer the dough for the proofing (cover with plastic wrapper or a wet clean gauze). Wait for 2-3 hours until the dough is doubled in size. Do not over proof in hot days; you will need to watch out the dough.',
      'In a large bowl, marinate the ground pork with all the seasonings. Set aside for at least 15 minutes. You can prepare this in previous day and keep the pork in refrigerator overnight.',
      'Heat up 2 tablespoons of cooking oil in wok and fry ground pork until aroma and separated. And then add smashed garlic, carrot and celery. Give a small pinch of salt and continue fry for 1-2 minutes until the celery and carrot are slightly soft. Transfer out and cool down.',
      'Line your steamer and prepare for the assembling process.',
      'When the dough is doubled in size, transfer to a slightly floured board and pinch the air out. Please knead forcefully for a smooth surface. Cut the dough into halves. Take one half out and cover the rest half with wet gauze so it will not dry out.',
      'Continue kneading the half dough for several minutes until there is no air inside any more (no small holes in the transection). Shape the dough into a long log and cut into 8 equal portions.',
      'Take one portion out, press down slightly and then roll to a around wrappers around 10 cm in diameter. Make the edges thinner than the center. Place on portion of the filling on the round wrapper and then seal completely. Repeat to finish all the buns.',
      'Repeat the two above steps to finish the other half bun.',
      'Set up the steamer and let the buns reset for around 10 to 15 minutes with lid covered.',
      'Steam on high heat for around 15 minute to 20 minutes. Turn off the fire, wait for 5 minutes before uncovering and enjoying.',
    ],
    duration: 176,
    complexity: Complexity.challenging,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm31',
    title: 'Tom Yum Goong',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4vgY0gdOlBIyYvm61yzRHGvnB6iwZH_4bAQ&usqp=CAU',
    categories: ['c4', 'c7', 'c8', 'c9'],
    ingredients: [
      '3 chili peppers',
      '5 sprigs cilantro',
      '2 tablespoon fish sauce',
      '3 kaffir lime leaves',
      '1 lemongrass',
      '1-2 limes',
      '5 Mushrooms',
      '1 tablespoon Nam Prig Pow Optional',
      '1 cup shrimp',
      '4 cups water',
    ],
    steps: [
      'Boil water in a 2 quart pot. Peel and de-vein the shrimp and set them aside. Cut lemon grass into pieces, 5-6 inches long. Use the back of your knife to pound the lemon grass, just to bruise it to release the flavor. Tie the lemon grass into a knot to make it easier to manage. Drop the lemon grass in water and let boil for 5 minutes.',
      'Put the fish sauce and 1 lime juice into the bottom of the bowls you will serve the soup in. Crush chili pepper and add to the bowl.',
      'Remove the stems from the kaffir lime leaves and add the leafy part to the pot. Clean and halve the mushrooms and add them to the pot. Let it boil. Add the shrimp and turn off the heat. Shrimp gets tough very quickly, and will cook even when it is just sitting in the warm broth. Scoop the shrimp and liquid into the serving bowls immediately. As soon as you add the liquid to the serving bowl, you will see that the broth becomes cloudy because of the lime juice. Add the nam prig pow. Sprinkle with cilantro and serve.',
      'Be very careful, the peppers can be hot. Take a small sip at a time. Add more fish sauce and/or lime juice if it tastes bland.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: false,
    isVegan: false,
  ),
  Meal(
    id: 'm32',
    title: 'Vegan Mango Salad',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRscV6twlhBDzTbjTleeWC9o5Zw2ndM7mA7A&usqp=CAU',
    categories: ['c4', 'c7', 'c8'],
    ingredients: [
      '1 green mango',
      '1/2 - 3/4 cup Toasted Peanuts',
      '1/2 teaspoon sugar',
      '1-2 shallots',
      '1 pinch salt',
      '1 lime',
      '1 chili pepper',
      'ground dried chili pepper',
    ],
    steps: [
      'Toast the peanuts in a pan for 10-15 minutes over a medium to medium-low heat. It takes a while to cook the raw peanuts thoroughly. When done, let the peanuts cool. Peel the green mango and shred it with the shredder until you hit the single large seed. Slice the peppers and shallots thinly.',
      'Put all the ingredients in a large bowl and mix well. Taste to see if you need lime juice. With a natural product like mango, the sourness varies depending on the variety and how green the mango is. Add lime juice as much as you like, start with a small amount first and keep adding until you hit the right spot. I usually start with ⅓ of a lime. Adjust the taste to your liking. Add ground chili for a spicier salad. If your salad is very spicy, you may need more seasonings.',
      'Serve as an appetizer or with the meal.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm33',
    title: 'Pad thai',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT3rlAg8NB4Q92ileIsGuARbP8Gv76BlQnOw&usqp=CAU',
    categories: ['c4', 'c6', 'c7', 'c8'],
    ingredients: [
      '1/2 package Thai rice noodles',
      '1-1/3 cup bean sprouts ',
      '1/2 banana flower',
      '1-1/2 cup Chinese chives ',
      '2 tablespoon cooking oil',
      '2 tablespoons tamarind paste',
      '2 tablespoon sugar',
      '1 minced shallots',
      '1 tablespoon preserved turnip',
      '1/3 cup extra firm tofu',
      '1/2 lime',
      '2 tablespoons peanuts ',
      '1/2-1/4 lb shrimp ',
      'ground pepper',
      '1/2 teaspoon ground dried chili pepper',
      '3 cloves minced garlic',
      '4 teaspoons fish sauce',
      '1 egg',
    ],
    steps: [
      'Start with soaking the dry noodles in lukewarm or room temperature water while preparing the other ingredients. Getting the noodles just right is the trickiest part of making Pad Thai. Make sure that the noodles are submerged in plenty of water. Check out Tips and Substitutions for in depth explanations. By the time you are ready to put ingredients in the pan, the noodles should be flexible but not mushy. Julienne tofu and cut into 1 inch long matchsticks. When cut, the super firm tofu/pressed tofu should have a mozzarella cheese consistency. You can fry the tofu separately until golden brown and hard, or you can fry with other ingredients below.',
      'Cut the Chinese chives into 1 inch long pieces. Set aside a few fresh chives for a garnish. Rinse the bean sprouts and save half for serving fresh. Mince shallot and garlic together.',
      'Use a wok or a large cast iron pan. If you do not have a wok, any big pot will do. Heat it up on high heat and pour oil in the wok. Fry the peanuts until toasted and remove them from the wok. The peanuts can be toasted in the pan without oil as well. Add shallot, preserved turnip, garlic and tofu and stir them until they start to brown. The noodles should be flexible but not expanded at this point.',
      'Drain the noodles and add to the wok. Stir quickly to keep things from sticking. Add tamarind, sugar, fish sauce and chili pepper. Stir. The heat should remain high. If your wok is not hot enough, you will see a lot of juice in the wok at this point. Turn up the heat, if it is the case.',
      'Make room for the egg by pushing all noodles to the side of the wok. Crack the egg into the wok and scramble it until it is almost all cooked. Fold the egg into the noodles. The noodles should soft and chewy. Pull a strand out and taste. If the noodles are too hard (not cooked), add a little bit of water. When you get the right taste, add shrimp and stir. Sprinkle white pepper around. Add bean sprouts and chives. Stir a few more times. The noodles should be soft, dry and very tangled.',
      'Pour onto the serving plate and sprinkle with ground pepper and peanuts. Serve hot with the banana flower slice, a wedge of lime on the side, raw Chinese chives and raw bean sprouts on top.',
      'As always, in Thailand, condiments such as sugar, chili pepper, vinegar and fish sauce are available at your table for your personal taste. Some people add more chili pepper or sugar at the table.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm34',
    title: 'som tum',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbHbnqdpWQ8v_Wyd9SolSo7VDBnqK6FA4rjw&usqp=CAU',
    categories: ['c4', 'c7', 'c8'],
    ingredients: [
      '5 Cherry Tomatoes',
      '1 - 5 chili peppers',
      '1 tablespoon dried shrimp',
      '1 tablespoon fish sauce',
      '1-2 cloves garlic',
      '2 cups shredded green papaya',
      '1 lime',
      '1 1/2 Palm Sugar',
      '2 tablespoons toasted peanuts',
      '1 - 2 Salted Crab',
      '3 Yardlong Beans',
    ],
    steps: [
      'If you have shredded green papaya, skip to the next step. Otherwise, cut the stem out of the papaya and peel only one side.',
      ' The skin will keep the papaya from slipping out of your hand while you are shredding it. Shred or grate the papaya.  You can use a papaya shredder or large hole cheese grater.',
      'Add the crab to a microwaveable bowl and cover the crab with water.',
      ' Either use a large bowl or put a plate under it. The water will boil over.',
      ' Microwave the crab for 5 minutes. You can also boil it in a pot over the stove for 5 minutes, too. ',
      'The crab should turn reddish similar to other cooked shellfish (picture 3.) Let the crab sit in hot water.',
      'Trim each end of the beans and cut them into 1 ½ inch pieces. Halve the tomatoes. Roast peanuts or use roasted peanuts.',
      ' Roast peanuts by constantly stirring peanuts in a pan for until lightly brown, about 7 minutes,depending on your heat.',
      'There are several ways you can make or mix som tum. There are 2 methods below, the traditional method that is used in Thailand and a cobbled up method for those without the tools (som tum mortar and pestle).',
    ],
    duration: 15,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm35',
    title: ' Pad Kee Mao',
    imgURL: 'https://static0.thaitable.com/images/recipe/5pad-kee-mao.jpg',
    categories: [
      'c4',
      'c6',
      'c7',
      'c8',
    ],
    ingredients: [
      '2 tablespoons cooking oil',
      '3 Sweet Peppers',
      '1 Thai chili pepper',
      '4 cloves garlic',
      '1 teaspoon fish sauce',
      '1 teaspoon sugar',
      '2 teaspoons soy sauce',
      '2 cups thinly sliced pork',
      '1 cup holy basil',
    ],
    steps: [
      'Chop garlic and chili peppers. You can use any combination of peppers for their heat and colors. With this recipe, I use one Thai hot chili for the heat. The rest are sweet peppers. Pick the holy basil from stems. Thinly slice the pork.',
      'Add cooking oil to a wok or pan, using high heat. When the mixture of hot chili and garlic hits the hot oil, the fumes may irritate your eyes and nose -- make sure your kitchen is well ventilated. With just one hot pepper, everyone in the vicinity was coughing and sneezing.',
      'Add the mixture of garlic and chili peppers in. Let it cook briefly, then add the pork. Stir until the pork starts to turn brown. You should see the juice pooling. Add soy sauce, fish sauce and sugar. When the pork is cooked, taste to see if you like the seasoning.',
      'When the pork is ready, add the noodles. Stir to mix the noodles in with the pork. If you want to taste the noodles again, this is a good time.',
      'Add holy basil and stir until the holy basil is incorporated into the noodles. Turn off the heat and serve hot with jasmine rice.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm36',
    title: ' Crab Fried Rice ',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHoqBWKRwZCvzBx8v4wORAMHtCdp85s-mPGw&usqp=CAU',
    categories: ['c4', 'c6', 'c9', 'c8'],
    ingredients: [
      '6 cups cooked rice',
      '2 eggs',
      '1 1/2 tablespoons fish sauce',
      '3 cloves chopped garlic',
      '2-3 chopped green onions',
      '3-5 tablespoons cooking oil',
      '1 teaspoon ground white pepper',
      '1 cup crab meat',
    ],
    steps: [
      'I cook 3 cups of jasmine rice with 3 cups of water which yields about 7 cups of cooked rice. '
          'This recipe calls for 6 cups of cooked rice.',
      'Another cup is for emergency rescue. Canned crab meat is convenient and fast.',
      'However,if you have leftover cooked crab, that is ideal. ',
      'The can that I bought has ½ cup of crab meat.',
      ' You will need 2 cans.',
      'Squeeze out the water so that the fried rice will be fluffy not gummy.',
      'Over medium to high heat, add 3 tablespoons of oil to a wok or a large pot.',
      ' You will need room to stir the rice around.',
      'Add chopped garlic to the oil.',
      ' When the garlic begins to brown, add rice. ',
      'Stir and mix the rice with the oil.',
      'Add crab meat and stir again.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm37',
    title: 'Chicken Basil',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ40G9EGCu8IWI_YhhtLMRj0g_dcnHDZ5nnqfi7HWSyp6XaFslsxwAPJ7f8nE0QvLtc-hY&usqp=CAU',
    categories: ['c4', 'c6', 'c9', 'c8'],
    ingredients: [
      '3 tablespoons fish sauce',
      '1 tablespoon minced garlic',
      '1/2 lb ground chicken',
      '1-2 packages holy basil',
      '4-7 minced Thai chili pepper',
      '2 tablespoons cooking oil',
    ],
    steps: [
      'Mince garlic and chili pepper together. Clean and pick holy basil leaves from their stems.',
      'It may appear like a lot of leaves, but the leaves will shrink when cooked and this flavor comes from the leaves.',
      'Fry the garlic and chili pepper in oil over high heat.',
      'When garlic starts to turn brown, drop the ground chicken ',
      'Stir constantly.',
      'The juice will start to come out. Keep stirring until all the juice is gone.',
      'It might take a couple of minutes.',
      'Add fish sauce. Then add holy basil.',
      'Quickly turn it over a few times to mix the leaves with the meat and then remove from the heat and put the gai pad ga pow in the serving plate or dishes.',
      'Serve hot with rice.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm38',
    title: 'Tom Kha Gai',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8-xsUHRKob_z8cXbenn5xz_tj6xBKk2wRMX508D-qGlbUPlA&s',
    categories: ['c4', 'c7', 'c8', 'c9'],
    ingredients: [
      '1/4 cup chicken',
      '2-4 sprigs cilantro',
      '1/4 cup coconut milk',
      '1 tablespoon fish sauce',
      '1 piece crushed galangal',
      '1-2 kaffir lime leaves',
      '1 lime',
      '2-3 Thai chili pepper',
      '1 1/2 cup water',
    ],
    steps: [
      'Crush a piece of galangal, 1 inch thick with the flat part of a cleaver or meat tenderizer (or you can be civilized and slice it). Drop the galangal, coconut milk and water, into a 2 quart pot. Let the pot boil at medium to low heat. Reduce heat to simmer and stir frequently, otherwise the coconut milk will curdle. Add sliced chicken and fish sauce. If you have the kaffir lime leaves, remove the central stem from the leaves and add kaffir lime leaves to the soup. Let boil again and turn off the heat.',
      'In serving bowls, add crushed fresh Thai chili pepper. Watch out for the crushed chili, it will clear your sinus better than wasabi. If you do not like it hot, do not crush the peppers, just float them for decoration. Squeeze the 1/3 of a lime in each bowl. Pour the soup in bowls and add cilantro for garnish. Serve hot.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm39',
    title: 'Shredded Coconut',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpLC-tiL5FdoDNN8ItmB4hxxr5X_GJ8jyeKQ&usqp=CAU',
    categories: ['c4', 'c7'],
    ingredients: [
      '1 ear corn',
      '1/2 teaspoon salt',
      '1 tablespoon sugar',
      '1/3 cup Shredded Coconut',
    ],
    steps: [
      'Boil enough water in a pot to cover the corn. Peel the husks and discard them or save them for containers. I cut the corn in half to fit into my pot. Boil the corn for less than a minute, just to cook the corn without leaching out the sweet juice. Make sure you turn the each side to submerge it under water. You can see the cooked kernels with bright yellow as opposed to dull yellow. Drain the water and let the corn cool down.',
      'If you use the frozen shredded coconut, thaw it in the microwave for 20 seconds or so. Fluff the shredded coconut.',
      'When the corn is cooled enough to handle, slice the corn from end to end. You may get about 1 cup of corn.',
      'Plate the corn in a container or plate. We use corn husks here as a container. Fold and tuck the ends, secure it with half of a toothpick. Spoon the corn into the husk, sprinkle about 2 teaspoon of shredded coconut, sprinkle ½ teaspoon of sugar and a pinch of salt on top of the coconut. Serve at room temperature and enjoy.',
    ],
    duration: 7,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm40',
    title: 'Laab',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8vG0Lokt9Nk4JtYBkt_UG5O4IDm7rXaFpxQ&usqp=CAU',
    categories: ['c4', 'c6', 'c7', 'c8'],
    ingredients: [
      '5 sprigs sliced cilantro',
      '3 tablespoons fish sauce',
      '1 sliced green onion ',
      '1/4 tablespoon ground dried chili pepper',
      '1/2 lbs ground pork',
      '1-2 limes',
      '1/4 thinly sliced shallots',
      '3 sprigs spearmint',
      '1 tablespoon toasted rice',
    ],
    steps: [
      'Squeeze juice from 1/3 of the lime on to the ground pork. Mix well and let it marinate for just a couple of minutes until you are ready to cook it.',
      'Heat up a pan on high until it is very hot. Add two tablespoons of water and then immediately add your marinated pork and stir. ',
      'The pork will stick to the pan at first, but then the juice will come out and the meat will loosen from the bottom. ',
      'Keep stirring until the pork is well done.',
      'Traditionally, the pork is undercooked, but I do not recommend undercooking pork for health reasons.',
      'Put the pork in a bowl a large mixing bowl that will hold all the ingredients. ',
      'Add fish sauce, green onion, shallot, cilantro, the rest of the lime juice, ground chili pepper and almost all of toasted rice into the bowl.',
      'Save some toasted rice to sprinkle on top for garnish.',
      ' Mix well and taste. It should be a little bit hot.',
      'You should be able to taste tartness from the lime juice and the fish sauce.',
      'If you need to add more fish sauce or lime juice, do not be afraid.',
      ' Getting the flavor balance right is a trial and error process.',
      'Put the mixed ingredients in a serving bowl, garnish with spearmint and sprinkle the rest of toasted rice on top.',
      ' Serve with vegetables like cabbage, green beans, lettuce and Thai basil.',
    ],
    duration: 10,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm51',
    title: 'Kimchi stew ',
    imgURL:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fchefjulieyoon.com%2Fwp-content%2Fuploads%2F2016%2F01%2FSoondubu-19-1-500x375.jpg&tbnid=tCg3DD9XLuKTkM&vet=10CKMBEDMopAFqFwoTCIDK-tSR2oEDFQAAAAAdAAAAABAD..i&imgrefurl=https%3A%2F%2Fchefjulieyoon.com%2F2016%2F01%2Fkimchi-soondubu-jjigae-kimchi-soft-tofu-stew%2F&docid=a3LnP32TFznn5M&w=500&h=375&q=Kimchi%20stew&client=firefox-b-d&ved=0CKMBEDMopAFqFwoTCIDK-tSR2oEDFQAAAAAdAAAAABAD_',
    categories: ['c5', 'c6', 'c7', 'c8'],
    ingredients: [
      '1 pound kimchi, cut into bite size pieces',
      '¼ cup kimchi brine',
      '½ pound pork shoulder (or pork belly)',
      '½ package of tofu (optional), sliced into ½ inch thick bite size pieces',
      '3 green onions',
      '1 medium onion, sliced (1 cup)',
      '1 teaspoon kosher salt',
      '2 teaspoons sugar',
      '2 teaspoons gochugaru (Korean hot pepper flakes)',
      '1 tablespoon gochujang (hot pepper paste)',
      '1 teaspoon toasted sesame oil',
      '2 cups of anchovy stock (or chicken or beef broth)',
      '7 large dried anchovies, heads and guts removed',
      '⅓ cup Korean radish (or daikon radish), sliced thinly',
      '4×5 inch dried kelp',
      '3 green onion roots',
      '4 cups water',
      'Place the kimchi and kimchi brine in a shallow pot. Add pork and onion',
    ],
    steps: [
      'Put the anchovies, daikon, green onion roots, and dried kelp in a sauce pan.',
      'Add the water and boil for 20 minutes over medium high heat.',
      'Lower the heat to low for another 5 minutes.',
      'Strain.',
      'Slice 2 green onions diagonally and add them to the pot.',
      'Add salt, sugar, hot pepper flakes, and hot pepper paste. Drizzle sesame oil over top and add the anchovy stock.',
      'Cover and cook for 10 minutes over medium high heat.',
      'Open and mix in the seasonings with a spoon. Lay the tofu over top.',
      'Cover and cook another 10 to 15 minutes over medium heat.',
      'Chop 1 green onion and put it on the top of the stew. Remove from the heat and serve right away with rice.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm52',
    title: 'Cold soba with dipping sauce',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvmfOn5BsSbMtK3mJNu8UHpzZjuoQFcZ20ig&usqp=CAU',
    categories: ['c5', 'c6', 'c7', 'c8'],
    ingredients: [
      '3 bundles (about 390 grams) of soba (buckwheat noodles)',
      '1 tablespoon wasabi sauce (from a tube of paste or made from wasabi powder)',
      '2 ounces (about 60 grams) peeled daikon or Korean radish',
      '3 green onions, chopped',
      '1 sheet of gim (seaweed paper)',
      '½ cup plus 1 tablespoon tsuyu sauce',
      '½ cup icy cold water',
      'About ½ cup ice cubes, optional',
    ],
    steps: [
      'Combine 2 teaspoons wasabi powder and 2 teaspoons water in a small bowl. Mix well and cover. Set aside.',
      'Grate the daikon and transfer to a strainer over a bowl. Set aside.',
      'Toast the both sides of the seaweed paper until it’s very crunchy. Shred thinly with kitchen scissors, and keep it in a plastic bag to keep it from getting soggy. Set aside.',
      'Combine the tsuyu sauce and the cold water in a small bowl. Stir it to mix well. Set aside.',
      'Bring a pot of water to a boil and add the noodles. Stir them with a wooden spoon to prevent them from sticking to each other.',
      'Cover and cook for 6 to 7 minutes over medium high heat. If it boils over, crack the lid a bit or keep it off.',
      'About 6 minutes later, take a sample of the noodles and taste it. If it’s cooked nicely, remove from the heat. If it’s still a little uncooked, cook 1 or 2 minutes longer.',
      'Drain the noodles through a strainer. Rinse them under cold running water, rubbing with both hands until the noodles get cold and not slippery anymore. As a final step, fill a large bowl with cold water with some ice cubes, to make the noodles very cold and chewier.',
      'Drain and make 6 equal size bundles. Place them on a bamboo mat on a large platter.',
      'Sprinkle some chopped green onion over top of each bundle and add some shredded gim, too.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm53',
    title: 'Kimchi pancake',
    imgURL:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages.slurrp.com%2Fprod%2Frecipe_images%2Fno-recipes%2Fkimchijeon-kimchi-pancakes-recipe-1649689332_XBXWF5XPJGZ7UJZJGLPJ.webp%3Fimpolicy%3Dslurrp-20210601%26width%3D1200%26height%3D675&tbnid=sebstvlhGGG9UM&vet=10CCYQMyhzahcKEwjwpcCkmNqBAxUAAAAAHQAAAAAQAw..i&imgrefurl=https%3A%2F%2Fwww.slurrp.com%2Frecipes%2Fkimchijeon-kimchi-pancakes-recipe-1649689332&docid=Um1S17Xwaz_fdM&w=1013&h=675&q=Kimchi%20pancake&client=firefox-b-d&ved=0CCYQMyhzahcKEwjwpcCkmNqBAxUAAAAAHQAAAAAQAw',
    categories: ['c5', 'c7', 'c8'],
    ingredients: [
      '½ pound well-fermented napa cabbage kimchi, chopped into small pieces, plus 2 tablespoons of the brine',
      '3 scallions, chopped',
      '½ teaspoon sugar',
      '½ cup all-purpose flour',
      '½ cup water',
      '4 tablespoons vegetable oil',
    ],
    steps: [
      'Combine the kimchi, kimchi brine, scallions, sugar, flour, and water in a medium bowl and mix well with a spoon.',
      'Heat a 12-inch nonstick skillet over medium heat. (If you don’t have a 12-inch skillet, use a smaller skillet to make 2 pancakes.',
      'Add 2 tablespoons of the vegetable oil and swirl to coat the bottom of the pan.',
      'Pour the batter into the pan and spread it with the back of a spoon or a spatula to make a large circle.',
      'Cook until the bottom is golden brown and crisp, 3 to 5 minutes.',
      'Carefully turn the pancake over. Drizzle the remaining 2 tablespoons oil around the edges of the skillet, then lift the pancake with a thin spatula to allow the oil to run underneath and tilt the pan to spread it evenly.',
      'Cook until the bottom of the pancake is light golden brown and crisp, 3 to 5 minutes.',
      'Flip it one more time and cook for another minute.',
      'Slide onto a large serving platter and serve immediately.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm54',
    title: 'Tteokbokki',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2gG78apr4R7SsDi1_Ohq8s9SSPfXgblJcHA&usqp=CAU',
    categories: ['c5', 'c7', 'c8'],
    ingredients: [
      '1 pound of cylinder shaped rice cake (tteok), bought or homemade. (Use a little more if you’re not adding hard boiled eggs and fish cakes)',
      '4 cups of water',
      '7 large size dried anchovies, with heads and intestines removed',
      '6 x 8 inch dried kelp',
      '⅓ cup hot pepper paste (gochujang)',
      '1 tablespoon Korean hot pepper flakes (gochugaru) aka “Korean chili flakes”',
      '1 tablespoon sugar',
      '3 green onions (scallions), cut into 3 inch long pieces',
      '2 hard boiled eggs, shelled (optional)',
      '½ pound fish cakes (optional)',
    ],
    steps: [
      'Add the water, dried anchovies, and dried kelp to a shallow pot or pan.',
      'Boil for 15 minutes over medium high heat without the lid.',
      'Combine gochujang (hot pepper paste), gochugaru (hot pepper flakes), and sugar in a small bowl. Remove the anchovies and kelp from the pot and add the rice cake, the mixture in the bowl, the green onion, and the optional fish cakes and hard boiled eggs. The stock will be about 2½ cups.',
      'Stir gently with a wooden spoon when it starts to boil. Let it simmer and keep stirring until the rice cake turns soft and the tteokbokki sauce thickens and looks shiny, which should take about 10 to 15 minutes. If the rice cake is not soft enough, add more water and continue stirring until it softens. When you use freshly made rice cake, it takes shorter time. If you use frozen rice cake, thaw it out and soak in cold water to soften it before cooking.',
      'Remove from the heat and serve hot. If you have any leftovers, just keep them in the fridge and reheat them when you want to eat. You should finished it in a few days.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm55',
    title: 'Wanja-jeon ',
    imgURL:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2FelcH2ebWXLQ%2Fmqdefault.jpg&tbnid=lo_cVZhtdlyl6M&vet=12ahUKEwiyybyRn9qBAxXemmMGHbO_AD8QMygfegUIARCPAQ..i&imgrefurl=https%3A%2F%2Fwww.maangchi.com%2Frecipe%2Fwanja-jeon&docid=67TtvkT7be4uHM&w=320&h=180&q=Wanja-jeon%20&client=firefox-b-d&ved=2ahUKEwiyybyRn9qBAxXemmMGHbO_AD8QMygfegUIARCPAQ',
    categories: ['c5', 'c7', 'c8'],
    ingredients: [
      '½ pound ground beef (or pork or mixture of pork and beef)',
      '4 ounces of tofu, squeezed out excess water',
      '3 tablespoons chopped onion',
      '1 garlic clove, minced',
      '1 green onion, chopped',
      '1 to 2 tablespoons chopped carrot',
      '½ teaspoon soy sauce',
      '¼ teaspoon ground black pepper',
      '1 to 2 teaspoons toasted sesame oil',
      '2 eggs and 1 egg yolk',
      '2 to 3 tablespoons all purpose flour',
      '3 tablespoons grapeseed oil (or vegetable oil)',
      'dill for garnish (optional)',
    ],
    steps: [
      'Combine ground beef, tofu, onion, garlic, green onion, carrot, 1 teaspoon kosher salt, soy sauce, ground black pepper, sesame oil and 1 egg in a bowl.',
      'Mix well by hand until the mixture gets a little sticky.',
      'Divide the mixture into 16 equal pieces. Roll each piece into a ball between your palms, then flatten into 2 inch disk and ¼ inch thick.',
      'Put the flour into a shallow bowl. Coat each patty with flour. Transfer to a platter. Repeat it with the rest of patties.',
      'Beat 1 egg, 1 egg yolk, and a pinch of salt in a bowl.',
      'Heat a large nonstick pan over medium heat. Add some oil and tilt the pan to spread it around.',
      'Working in batches, dip each patty in the beaten egg and place in the pan, one by one.',
      'Cook for about 1 minute until the bottom part turns light golden brown. Flip it over and cook for a few more minutes until the bottom part turns a little crunchy and light golden brown. Add more oil to the pan as needed.',
      'Turn and cook for another 30 seconds and transfer to a serving platter. Serve the patties hot or at room temperature.'
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: false,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm56',
    title: 'Doenjang-jjigae ',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLth_zpQanwdJbL-uW8wmN8pAd_RHzyfBp99fgGz70GlYgAAq86_iv-nhtDHlHiGScZsA&usqp=CAU',
    categories: ['c5', 'c6', 'c7', 'c8'],
    ingredients: [
      '1 medium potato, peeled and cut into ½-inch cubes (about 1 cup)',
      '1 medium onion, cut into ½-inch pieces (about 1 cup)',
      '1 small zucchini, cut into ½-inch pieces (about 1 cup)',
      '1 green Korean chili pepper (cheong-gochu), stemmed and chopped',
      '4 garlic cloves, minced',
      '4 large shrimp, shelled, deveined, washed, and coarsely chopped (about ⅓ cup)',
      '2½ cups water',
      '7 dried anchovies, guts removed',
      '5 tablespoons fermented soybean paste (doenjang)',
      '6 ounces medium-firm tofu, cut into ½-inch cubes (about 1 cup)',
      '2 green onions, chopped',
    ],
    steps: [
      'Combine the potato, onion, zucchini, chili pepper, garlic, and shrimp in a 1½-quart (6 cups) earthenware pot or other heavy pot.',
      'Wrap the dried anchovies in cheesecloth (or a dashi bag, a pouch for stock-making sold at a Korean grocery store), and put them into the pot with other ingredients  Add water and cover.',
      'Cook over medium-high heat for 15 minutes until it starts boiling. If you use a stainless steel pot, it will take less than 15 minutes, about 7 to 8 minutes.',
      'Stir in the soybean paste, mixing well. Cover and cook for 20 minutes longer over medium heat.',
      'Add the tofu and cook for another 3 minutes. Remove the anchovy pouch and discard.',
      'Sprinkle with the green onions and serve as a side dish to rice. Serve it directly from the pot, or transfer to a serving bowl. Everybody can eat together out of the pot, or portions can be ladled out in individual bowls for each person.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm57',
    title: 'Korean crab stew ',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYK-UykA14mjtTTWwgWkc9fSFZvJnaWb0xHg&usqp=CAU',
    categories: ['c5', 'c6', 'c7', 'c8'],
    ingredients: [
      '1 pound of cleaned Korean flower crabs (frozen or fresh), cut into chunks (or substitute with your local crab)',
      '7 large dried anchovies, guts removed',
      '5 ounces peeled Korean radish (or daikon radish), sliced thinly',
      '4 ounces of zucchini, sliced',
      '1 green onion, sliced',
      '1 green chili pepper, chopped',
      '1 red chili pepper (optional), chopped',
      '4 garlic cloves, minced',
      '1 small onion (4 ounces), sliced',
      '2 tablespoons Korean fermented soybean paste (doenjang)',
      '1 tablespoon Korean hot pepper paste (gochujang)',
      '1 to 2 teaspoons Korean hot pepper flakes (gochugaru) (optional)',
      'a few chrysanthemum greens (or substitute with basil leaves)',
    ],
    steps: [
      'Thaw the crabs out in the fridge for a couple of hours.',
      'Take them out. Cut the tips off the legs and cut the crabs into bite size pieces.',
      'Rinse in cold water and strain.',
      'Put the anchovies in a bag or tea strainer to keep them together. Add to a pot with 3½ cups water. Add radish, soybean paste, and hot pepper paste. Boil for 20 minutes over medium heat.',
      'Remove the anchovies.',
      'Add onion, zucchini, green onion, garlic, green chili pepper, and the crab. Cover and cook another 15 minutes over medium high heat until the crabs are well cooked and the radish looks translucent.',
      'Stir the stew with a spoon. Add the extra 1 teaspoon hot pepper flakes if you want it.',
      'Add chrysanthemum greens and red chili pepper as a garnish. Remove it from the heat and serve hot with rice and a few more side dishes.',
      'You can keep leftovers in the fridge for 3 or 4 days.',
    ],
    duration: 40,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: false,
  ),
  Meal(
    id: 'm58',
    title: 'Roasted seaweed sheets ',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI0DI05e6zM7M0BwZxzFqBiNMBVApTCOyTf_fS_3h2iqhROoCdNUxKK5b4SEunKwcoysU&usqp=CAU',
    categories: ['c5', 'c6', 'c7', 'c8'],
    ingredients: [
      '20 sheets of gim (seaweed sheets)',
      '2 tablespoons cooking oil',
      '2 teaspoons toasted sesame oil',
      '1 teaspoon kosher salt',
    ],
    steps: [
      'Combine the cooking oil and toasted sesame oil in a small bowl and put the salt in a small bowl. Place a few pieces of paper towel in front of you, where you can work.',
      'Put a sheet of gim on the paper towel with the shiny side up. Using your hand or a brush, spread a light layer of the oil mixture on the gim. Sprinkle a pinch of salt over top.',
      'Repeat until all 20 sheets oiled and seasoned with salt.',
      'Roll the seasoned gim up in the paper towel, so it soaks up a bit of the excess oil. Set aside.',
      'Heat up a large pan on the stove over medium heat, or heat a griddle to 350°F (about 180°C).',
      'Place a sheet of gim with the shiny side up on the griddle. Press the gim with a spatula for about 15 seconds until the bottom turns crispy and green.',
      'Add another sheet of gim on top of the first, with the rough side up. Flip them over and add another sheet of gim with the rough side up. Cook for about 15 seconds. Repeat this until all 20 sheets of gim turn very crispy and beautiful light green. Layering it this way will make the sheets crispier, as the inside sheets get roasted as you go. The key is to always keep the rough side out, so it ends up next to the grill and the shiny side in, so it never touches the grill.',
      'Remove from the heat. Cut them into bite size pieces. Serve with rice or as a side dish with beer.',
      'Keep the leftovers in a small sandwich bag or an airtight container and serve it over the next few days. If you roast a large quantity, keep the excess in the freezer, and only take it out as you need it.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm59',
    title: 'Kimchi fried rice ',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgSSr4AmIlgntht6MgtTmSVPz0d4Rhsm6Ivg&usqp=CAU',
    categories: ['c5', 'c6', 'c7', 'c8'],
    ingredients: [
      '3 bowls steamed rice (3 cups)',
      '1 cup chopped kimchi (should be aged, well-fermented and sour)',
      '¼ cup kimchi juice (spicy red juice from a jar of kimchi)',
      '¼ cup water',
      '2-3 tablespoons gochujang',
      '3 teaspoons toasted sesame oil',
      '1 teaspoon vegetable oil',
      '1 green onion, chopped',
      '1 tablespoon roasted sesame seeds',
      '1 sheet of gim, roasted and shredded into seaweed strips',
    ],
    steps: [
      'Heat up a wide, flat pan or skillet. Add the vegetable oil.',
      'Add the kimchi and stir fry for 1 minute over medium-high heat.',
      'Add rice, kimchi juice, water, and gochujang. Stir all the ingredients together for about 7 minutes with a wooden spoon.',
      'Add sesame oil and remove from the heat.',
      'Garnish with sprinkled chopped green onion, roasted gim, and sesame seeds. Serve right away.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
  Meal(
    id: 'm60',
    title: 'Fish-shaped bread with sweet red bean filling',
    imgURL:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDjdBAZyrMjb88i2rmdB4-M4vY9y7UXeoTAA&usqp=CAU',
    categories: ['c5', 'c6', 'c7', 'c8'],
    ingredients: [
      '1 cup all purpose flour',
      '½ teaspoon kosher salt',
      '½ teaspoon baking soda',
      '1 tablespoon brown or white sugar',
      '1 cup plus 2 tablespoons water',
      '1 tablespoon vegetable oil',
      'Sweet red beans (canned or homemade): for homemade, use the method from my patbingsu recipe',
    ],
    steps: [
      'Combine flour, kosher salt, baking soda, and sugar in a bowl. Add water and mix it well.',
      'Sieve the mixture through a strainer to get a silky batter without any lumps.',
      'Heat up the bunggeoppang pan and turn the heat down to low.',
      'Open the pan and grease both the upper and lower fish molds with a light coating of vegetable oil.',
      'Pour the batter into one side of the fish mold until it’s ⅓ full. Add  1 tablespoon of sweet red beans to the center, and then gently fill up the rest of the fish mold to totally cover the red beans.',
      'Close the mold and cook for about 3 minutes over low heat.',
      'Turn the pan over and let it cook another 3 minutes. Open it and turn it over again for another 30 seconds, to make the bread a little more crispy.',
      'Take out and serve immediately.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    isGluton: true,
    isLuctose: true,
    isVegan: true,
  ),
];
